// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package fanout_test

import (
	"testing"

	fastly "github.com/fastly/go-fastly/v9/fastly"
	fanout "github.com/fastly/go-fastly/v9/fastly/products/fanout"
)

func Test_Get_validation(t *testing.T) {
	if _, err := fanout.Get(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Enable_validation(t *testing.T) {
	if _, err := fanout.Enable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Disable_validation(t *testing.T) {
	if err := fanout.Disable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}
