// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package ngwaf

import fastly "github.com/fastly/go-fastly/v9/fastly"

// Get gets the status of the Next-Gen WAF product on the service.
func Get(c *fastly.Client, serviceID string) (*fastly.ProductEnablement, error) {
	if serviceID == "" {
		return nil, fastly.ErrMissingServiceID
	}

	path := fastly.ToSafeURL("enabled-products", "v1", "ngwaf", "services", serviceID)

	resp, err := c.Get(path, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var h *fastly.ProductEnablement
	if err := fastly.DecodeBodyMap(resp.Body, &h); err != nil {
		return nil, err
	}
	return h, nil
}

// Enable enables the Next-Gen WAF product on the service.
func Enable(c *fastly.Client, serviceID string, i *EnableInput) (*fastly.ProductEnablement, error) {
	if serviceID == "" {
		return nil, fastly.ErrMissingServiceID
	}
	if err := i.Validate(); err != nil {
		return nil, err
	}

	path := fastly.ToSafeURL("enabled-products", "v1", "ngwaf", "services", serviceID)

	resp, err := c.PutJSON(path, i, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var h *fastly.ProductEnablement
	if err := fastly.DecodeBodyMap(resp.Body, &h); err != nil {
		return nil, err
	}
	return h, nil
}

// Disable disables the Next-Gen WAF product on the service.
func Disable(c *fastly.Client, serviceID string) error {
	if serviceID == "" {
		return fastly.ErrMissingServiceID
	}

	path := fastly.ToSafeURL("enabled-products", "v1", "ngwaf", "services", serviceID)

	resp, err := c.Delete(path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// GetConfiguration gets the configuration of the Next-Gen WAF product on the service.
func GetConfiguration(c *fastly.Client, serviceID string) (*ConfigureOutput, error) {
	if serviceID == "" {
		return nil, fastly.ErrMissingServiceID
	}

	path := fastly.ToSafeURL("enabled-products", "v1", "ngwaf", "services", serviceID, "configuration")

	resp, err := c.Get(path, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var h *ConfigureOutput
	if err := fastly.DecodeBodyMap(resp.Body, &h); err != nil {
		return nil, err
	}
	return h, nil
}

// UpdateConfiguration updates the configuration of the Next-Gen WAF product on the service.
func UpdateConfiguration(c *fastly.Client, serviceID string, i *ConfigureInput) (*ConfigureOutput, error) {
	if serviceID == "" {
		return nil, fastly.ErrMissingServiceID
	}
	if err := i.Validate(); err != nil {
		return nil, err
	}

	path := fastly.ToSafeURL("enabled-products", "v1", "ngwaf", "services", serviceID, "configuration")

	resp, err := c.PutJSON(path, i, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var h *ConfigureOutput
	if err := fastly.DecodeBodyMap(resp.Body, &h); err != nil {
		return nil, err
	}
	return h, nil
}
