// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package ngwaf_test

import (
	"testing"

	fastly "github.com/fastly/go-fastly/v9/fastly"
	ngwaf "github.com/fastly/go-fastly/v9/fastly/products/ngwaf"
)

func Test_Get_validation(t *testing.T) {
	if _, err := ngwaf.Get(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Enable_validation(t *testing.T) {
	for _, tc := range EnableInputTestCases["valid"] {
		if _, err := ngwaf.Enable(fastly.TestClient, "", &tc.Input); err != fastly.ErrMissingServiceID {
			t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
		}
	}
	for _, tc := range EnableInputTestCases["invalid"] {
		_, err := ngwaf.Enable(fastly.TestClient, fastly.TestDeliveryServiceID, &tc.Input)
		if tc.WantError != nil && err != tc.WantError {
			t.Fatalf("expected '%s', got: '%s'", tc.WantError, err)
		}
	}
}

func Test_Disable_validation(t *testing.T) {
	if err := ngwaf.Disable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_GetConfiguration_validation(t *testing.T) {
	if _, err := ngwaf.GetConfiguration(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_UpdateConfiguration_validation(t *testing.T) {
	for _, tc := range ConfigureInputTestCases["valid"] {
		if _, err := ngwaf.UpdateConfiguration(fastly.TestClient, "", &tc.Input); err != fastly.ErrMissingServiceID {
			t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
		}
	}
	for _, tc := range ConfigureInputTestCases["invalid"] {
		_, err := ngwaf.UpdateConfiguration(fastly.TestClient, fastly.TestDeliveryServiceID, &tc.Input)
		if tc.WantError != nil && err != tc.WantError {
			t.Fatalf("expected '%s', got: '%s'", tc.WantError, err)
		}
	}
}
