// Code generated by 'service_product_enablement' generator, DO NOT EDIT.

package fastly

import tmpl "github.com/fastly/go-fastly/v9/internal/templates/product_brotli_compression"

// GetProductBrotliCompression gets the status of the BrotliCompression product on the service.
func (c *Client) GetProductBrotliCompression(serviceID string) (*ProductEnablement, error) {
	if serviceID == "" {
		return nil, ErrMissingServiceID
	}

	path := ToSafeURL("enabled-products", tmpl.ProductID, "services", serviceID)

	resp, err := c.Get(path, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var h *ProductEnablement
	if err := decodeBodyMap(resp.Body, &h); err != nil {
		return nil, err
	}
	return h, nil
}

// EnableProductBrotliCompression enables the BrotliCompression product on the service.
func (c *Client) EnableProductBrotliCompression(serviceID string) (*ProductEnablement, error) {
	if serviceID == "" {
		return nil, ErrMissingServiceID
	}

	path := ToSafeURL("enabled-products", tmpl.ProductID, "services", serviceID)

	resp, err := c.Put(path, nil)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var h *ProductEnablement
	if err := decodeBodyMap(resp.Body, &h); err != nil {
		return nil, err
	}
	return h, nil
}

// DisableProductBrotliCompression disables the BrotliCompression product on the service.
func (c *Client) DisableProductBrotliCompression(serviceID string) error {
	if serviceID == "" {
		return ErrMissingServiceID
	}

	path := ToSafeURL("enabled-products", tmpl.ProductID, "services", serviceID)

	resp, err := c.Delete(path, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}
