// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package ddos_protection_test

import (
	"testing"

	fastly "github.com/fastly/go-fastly/v9/fastly"
	ddosprotection "github.com/fastly/go-fastly/v9/fastly/products/ddos_protection"
)

func Test_Get_validation(t *testing.T) {
	if _, err := ddosprotection.Get(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Enable_validation(t *testing.T) {
	if _, err := ddosprotection.Enable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Disable_validation(t *testing.T) {
	if err := ddosprotection.Disable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}
