// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package image_optimizer_test

import (
	"testing"

	fastly "github.com/fastly/go-fastly/v9/fastly"
	imageoptimizer "github.com/fastly/go-fastly/v9/fastly/products/image_optimizer"
)

func Test_Get_validation(t *testing.T) {
	if _, err := imageoptimizer.Get(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Enable_validation(t *testing.T) {
	if _, err := imageoptimizer.Enable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Disable_validation(t *testing.T) {
	if err := imageoptimizer.Disable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}
