// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package websockets_test

import (
	"testing"

	fastly "github.com/fastly/go-fastly/v9/fastly"
	websockets "github.com/fastly/go-fastly/v9/fastly/products/websockets"
)

func Test_Get_validation(t *testing.T) {
	if _, err := websockets.Get(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Enable_validation(t *testing.T) {
	if _, err := websockets.Enable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Disable_validation(t *testing.T) {
	if err := websockets.Disable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}
