// Code generated by 'service_linked_product' generator, DO NOT EDIT.

package origin_inspector_test

import (
	"testing"

	fastly "github.com/fastly/go-fastly/v9/fastly"
	origininspector "github.com/fastly/go-fastly/v9/fastly/products/origin_inspector"
)

func Test_Get_validation(t *testing.T) {
	if _, err := origininspector.Get(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Enable_validation(t *testing.T) {
	if _, err := origininspector.Enable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}

func Test_Disable_validation(t *testing.T) {
	if err := origininspector.Disable(fastly.TestClient, ""); err != fastly.ErrMissingServiceID {
		t.Fatalf("expected '%s', got: '%s'", fastly.ErrMissingServiceID, err)
	}
}
