name: Generate changelog entry for Dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash

jobs:
  dependabot-changelog-update:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # add the Skip-Changelog label when the PR doesn't need an entry
    steps:
      - name: Generate a GitHub token
        id: github-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "go-fastly"
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.github-token.outputs.token }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: true

      - name: Generate changelog entry
        uses: dangoslen/dependabot-changelog-helper@50a0884d19a0e4aa379a69c96a82b5e8d6c46d63 # v4.2.1
        with:
          activationLabels: dependencies
          changelogPath: './CHANGELOG.md'
          entryPrefix: 'build(deps): '

      - name: Commit changelog entry
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "docs(CHANGELOG.md): add dependency bump from dependabot"
