name: Generate changelog entry for Dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash

jobs:
  dependabot-changelog-update:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # add the Skip-Changelog label when the PR doesn't need an entry
    steps:
      - name: Generate a GitHub token
        id: github-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "go-fastly"
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.github-token.outputs.token }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: true

      - name: Generate changelog entry
        uses: dangoslen/dependabot-changelog-helper@291c8cb629d7cd7b57ea065782c435ec2bedb138 # v4.3.0
        with:
          activationLabels: dependencies
          changelogPath: './CHANGELOG.md'
          entryPrefix: 'build(deps): '

      - name: Commit changelog entry
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "docs(CHANGELOG.md): add dependency bump from dependabot"
